import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import ThemeContextProvider from "@/context/theme-context";
import ThemeSwitch from "@/app/components/theme/theme-switch";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "relative bg-gray-50 pt-28 text-gray-950 dark:bg-gray-900 dark:text-gray-50 dark:text-opacity-90 sm:pt-36",
          fontSans.variable,
        )}
      >
        <ThemeContextProvider>
          {children}

          <ThemeSwitch />
        </ThemeContextProvider>
      </body>
    </html>
  );
}
