import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import ThemeContextProvider from "@/context/theme-context";
import ThemeSwitch from "@/app/components/theme/theme-switch";
import Header from "./components/header";
import ActiveSectionContextProvider from "@/context/active-section-context";
import { ReduxProvider } from "@/redux/provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "bg-primary text-primary dark:text-opacity-90",
          fontSans.variable,
        )}
      >
        <ActiveSectionContextProvider>
          <ThemeContextProvider>
            <Header />
            <ReduxProvider>{children}</ReduxProvider>
            <ThemeSwitch />
          </ThemeContextProvider>
        </ActiveSectionContextProvider>
      </body>
    </html>
  );
}
