name: "coverage"
on:
  pull_request:
    branches:
      - master
      - main

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: ArtiomTr/jest-coverage-report-action@v2.2.6
        with:
          working-directory: ./apps/server/
          package-manager: pnpm
          test-script: pnpm test
          coverage-script: pnpm test:coverage
